### ISSUE TITLE
CQ Pipeline failing for magazino_toru

### ISSUE THREAD

**Issue by cschuet** [magazino/cartographer_magazino#6]
CQ pipeline is failing with the error

```
[FATAL] [1520126832.225109750]: F0304 01:27:12.000000   349 lua_parameter_dictionary.cc:399] Check failed: HasKey(key) Key 'use_landmarks' not in dictionary:
```

The command that we are executing is

```
/bin/bash -c "source /opt/ros/kinetic/setup.bash && source /opt/cartographer_ros/setup.bash && /usr/bin/time -v roslaunch cartographer_toru offline_toru_2d.launch bag_filenames:=/data/5692462144159744/hallway_return.bag no_rviz:=true"
```

**Comment by cschuet** [comment]
I suppose https://github.com/magazino/cartographer_magazino/commit/ca05f9d04ba6bec2b258e0257c9c31433868f13b should fix that. Will close once verified.

**Comment by MichaelGrupp** [comment]
Yes, I had the same error in our daily cron job on Travis - should be fixed by the commit that adds the parameter.

**Comment by cschuet** [comment]
It's docker caching stuff it should not be caching. I am sure that commit will fix it once it actually is used in the pipeline.
